export const LATEST_PROJECTS = [
    {
        title: 'Next Generation Menu',
        description:
            'NGMenu (Next Generation Menu) is a robust solution designed to revolutionize restaurant management. With its comprehensive set of features and intuitive interface, NGMenu empowers restaurant owners, outlets, and developers to streamline operations, enhance customer experiences, and drive business growth. From efficient order management and real-time analytics to seamless integration with existing POS systems, NGMenu is the ultimate solution for modernizing and optimizing restaurant operations',
        image: '/assets/app/ngmenu.png',
        link: 'https://ngmenu.com',
        badges: [
            'NextJs',
            'Adonis',
            'Angular 16',
            'Tailwind',
            'Redis',
            'Socket io',
            'AWS',
            'Amazon Translate',
            'Stripe Connect',
            'Mail Gun',
        ],
    },

    {
        title: 'NG Cards',
        description: `NGCards is an innovative platform that redefines the way we share contact information. With its cutting-edge NFC technology, users can effortlessly create and customize their business cards, enabling seamless digital connections. By simply tapping their NFC-enabled devices, recipients can instantly download the contact information in vCard (vcf) file format, allowing their phones to easily recognize and store the details. NGCards simplifies networking and enhances professional interactions, providing a modern and efficient solution for sharing contact information in today's digital ag`,
        image: '/assets/app/ngcards.png',
        link: 'https://ngcards.com',
        badges: ['Laravel', 'Angular 16', 'Tailwind', 'Redis', 'AWS', 'Stripe'],
    },

    {
        title: 'Nadena',
        description: `Nadena is a comprehensive app designed for coaches and clients, offering a seamless platform for enhanced coaching experiences. Coaches can effortlessly monitor the activity and progress of their clients, providing personalized food and exercise recommendations from a vast library of workout plans and food plans. With built-in step tracking and seamless chat functionality, coaches can stay connected with their clients, offering support and guidance every step of the way. Nadena supports both Arabic and English languages, ensuring a tailored experience for users`,
        image: '/assets/app/nadena.png',
        link: 'https://nadena.ae',
        badges: [
            'NextJs',
            'NestJS',
            'Angular 16',
            'Ionic',
            'In App Purchase',
            'Xcode',
            'Android',
            'Play Store',
            'App Store',
            'Redis',
            'Socket io',
            'AWS',
            'Nutritionix',
            'spoonacular',
            'Mail Gun',
        ],
    },

    {
        title: 'Mawedy',
        description: `Mawedy is an enterprise-grade solution specifically designed for hospitals and clinics, providing a comprehensive platform to manage doctors, departments, patients, and services. Patients can conveniently book appointments through the app, whether it's with their trusted doctors or at the nearest clinic. The app also offers appointment reminders, notifying patients when they are near their scheduled appointments. With Mawedy, rescheduling or following up on checkups is a seamless experience. Doctors can access patients' medical records and history, even if the patient has only visited their clinic recently, as data is securely stored in the cloud. Moreover, patients can receive notifications via email, SMS, or cloud notifications, ensuring they stay updated and informed. Mawedy empowers hospitals and clinics with efficient, connected, and patient-centric healthcare services.`,
        image: '/assets/app/mawedy.png',
        link: 'https://mawedy.ae',
        badges: [
            'Laravel',
            'Angular 16',
            'Redis',
            'Socket io',
            'Expo',
            'React Native',
            'Google Cloud Services',
            'Play Store',
            'App Store',
            'AWS',
            'Stripe',
            'Mail Gun',
            'Vonage',
        ],
    },

    {
        title: 'Practical',
        description: `Practical is an e-commerce website specializing in pants, offering a seamless shopping experience for customers. The website incorporates Stripe payment integration, allowing customers to make purchases using convenient payment methods such as Apple Pay and Google Pay, as well as other supported payment options. The website is built on WordPress, providing a user-friendly interface for easy navigation and content management. Additionally, the admin panel is developed with Angular, empowering administrators with efficient management and control over the website's operations. Practical combines style, functionality, and convenience, providing customers with a reliable platform to explore and purchase pants online`,
        image: '/assets/app/practical.png',
        link: 'https://practical.ae',
        badges: [
            'Wordpress',
            'Laravel',
            'Angular 16',
            'Redis',
            'AWS',
            'Stripe',
            'Mail Gun',
        ],
    },

    {
        title: 'If it Fits your Macros',
        description: `IIFYM (If It Fits Your Macros) is a catering website catering to diet enthusiasts, including many celebrity clients. With a focus on personalized nutrition, clients can input their age, weight, activity level, and goals. The web app utilizes advanced recommendation algorithms to generate a 30-day meal plan tailored to their specific macros (macronutrient) requirements, BMI (Body Mass Index), and goals. Integration with Stripe enables secure and seamless payment processing for orders and subscriptions. The website also includes an admin panel that allows efficient management of deliveries and subscriptions, ensuring a smooth and reliable service. With IIFYM, clients can enjoy customized meal plans to support their fitness journey and achieve their desired health and wellness goals.`,
        image: '/assets/app/iifym.png',
        link: 'https://iifym.ae',
        badges: [
            'Adonis',
            'Angular 16',
            'Redis',
            'AWS',
            'Stripe',
            'Recommendation Algorithm',
            'Mail Gun',
        ],
    },

    {
        title: 'Thahabamaal',
        link: 'https://thahabamaal.ae',
        description: `Thahabamaal is an exquisite jewelry e-commerce platform owned by a celebrity. The website showcases a wide range of stunning jewelry pieces, offering customers a luxurious shopping experience. Thahabamaal integrates with both Tabby and Stripe, providing convenient payment options for customers. With Tabby, customers can take advantage of buy-now-pay-later options, while Stripe ensures secure and seamless transactions. The website also features an efficient admin panel that enables the management of content updates and order fulfillment. This allows the owner to maintain the website's product catalog, showcase new arrivals, and handle orders efficiently. With Thahabamaal, customers can indulge in the elegance of celebrity-inspired jewelry and enjoy a seamless online shopping experience`,
        image: '/assets/app/thahabamaal.png',
        badges: [
            'Laravel',
            'Angular 16',
            'Redis',
            'AWS',
            'Stripe',
            'Tabby',
            'Go Daddy Hosting',
        ],
    },

    {
        title: 'The Dungeon Dubai',
        link: 'https://thedungeon.ae',
        description: `The Dungeon Dubai is the ultimate destination for powerlifters, offering a wide range of gym accessories and clothing through its e-commerce platform. Owned by a prominent celebrity, the website caters specifically to the needs of powerlifting enthusiasts. Clients can conveniently pre-register for competitions and seminars, while also gaining access to comprehensive information such as competitor lists and leaderboards. The website features an intuitive admin panel for seamless management of e-commerce operations, competition participants, and content management system (CMS). With integrated Stripe and PassKit functionality, digital entry passes are effortlessly delivered to the client's Apple & Google Wallet, ensuring a hassle-free experience`,
        image: '/assets/app/thedungeon.png',
        badges: [
            'Angular 16',
            'Laravel',
            'Redis',
            'AWS',
            'Stripe',
            'Mail Gun',
            'Passkit',
        ],
    },
]
