export const WORK_EXPERIENCES = [
    {
        id: 1,
        dates: ['2021', 'Present'],
        position: 'Lead Engineer',
        company: 'Digital Brand Work Technology',
        link: location.origin + '/#/latest-projects',
        designation:
            'Team Leader, Scrum Master, Senior frontend engineer, full stack engineer, mobile engineer.',
        description:
            'As a visionary software engineer, I played a pivotal role in delivering cutting-edge, futuristic production code for esteemed clients, including industry leaders such as The Dungeon Dubai, Practical, IIFYM, Thahabamaal, Kroki, Mawedy, Nadena, NGCards, NGMenu, Rive, and more. Throughout my tenure, I consistently produced high-quality and robust solutions while assuming a leadership role within the engineering department. By fostering collaboration, facilitating knowledge sharing, and providing mentorship, I empowered team members to embrace the future of technology and innovation. Committed to staying updated with the latest industry trends and advancements, I effectively communicated and worked collaboratively in a team environment. My passion for driving forward-thinking approaches to software engineering ensured a results-oriented mindset focused on delivering innovative solutions. I successfully led projects to completion, garnering recognition for exceptional client satisfaction and surpassing project goals. In addition, I gathered and managed data for software inputs, developed and maintained software applications, adhered to clean and maintainable coding practices, and upheld the highest standards of code quality. By placing a strong focus on data integrity and accuracy, I supported informed decision-making. Collaborating closely with IT developers, users, and stakeholders, I streamlined security and maintenance processes. Remaining up to date with the latest technological advancements and best practices, I consistently drove innovation in software. My dedication was unwavering in delivering efficient and reliable solutions that met the unique needs of clients.',
        badges: [
            'Angular 16',
            'Ionic',
            'React',
            'React Native',
            'Tailwind',
            'Typescript',
            'NestJs',
            'SCSS',
            'Redux',
            'NGRX',
            'Rxjs',
            'Karma',
            'Angular MDC',
            'HTML',
            'CSS',
            'JQuery',
            'JavaScript',
            'PHP',
            'MySQL',
            'PostgreSQL',
        ],
    },

    {
        id: 3,
        dates: ['2020', '2021'],
        position: 'Project Lead Engineer',
        company: 'Iloilo Provincial Population Office',
        link: 'https://iloilo-pop.com/#/home/index/news',
        designation: 'Full Stack Web Engineer',
        description: `In my previous role, I was responsible for creating system designs and architectures to ensure seamless data management between websites and mobile apps. I developed complex frontend web applications using Angular and built mobile apps for iOS and Android using Expo and React Native. By focusing on robust component development, I ensured scalability and optimal performance. Additionally, I contributed to the back-end logic, managed documentation, and created a comprehensive user manual for provincial personnel. My expertise played a vital role in delivering comprehensive solutions for web and mobile platforms, serving the general public. Throughout my work, I implemented responsive design techniques, integrated third-party APIs and services, conducted thorough code reviews, collaborated with UI/UX designers, optimized application performance, utilized version control systems, participated in agile development processes, worked closely with QA testers, researched emerging technologies, and provided technical support and troubleshooting assistance to end-users.`,
        badges: [
            'Angular 5+',
            'SCSS',
            'Bootstrap',
            'Laravel',
            'React Native',
            'Expo',
        ],
    },

    {
        id: 4,
        dates: ['2019', '2020'],
        position: 'Project Sole Engineer',
        company: 'USAID, POPCOM, DOH',
        link: 'https://www.usaid.gov/',
        designation: 'Full Stack Web Engineer',
        description: `In my previous role, I created system designs and architectures to harmonize and integrate data between two government agencies sponsored by USAID. I designed databases and user interfaces, developed robust, maintainable, and reusable code for web systems, and prioritized delivering high-quality solutions aligned with industry best practices. My contributions enabled efficient data integration and provided a user-friendly experience for agency personnel. Collaborating effectively with cross-functional teams, I implemented security measures, optimized system performance, and conducted comprehensive testing to ensure stable and error-free applications.`,
        badges: ['HTML', 'CSS', 'JQuery', 'Javascript', 'PHP', 'MySql', 'OOP'],
    },

    {
        id: 5,
        dates: ['2017', 'Present'],
        position: 'Freelance Software Engineer',
        company: 'Iloilo Philippines',
        link: '/',
        designation: 'Full Stack Engineer',
        description: `As a highly skilled engineer with expertise in mobile, desktop, and web applications, I excelled in delivering innovative solutions. My experience encompassed various programming languages and frameworks, allowing me to create cutting-edge applications. I successfully integrated applications with IoT hardware components, showcasing my ability to leverage emerging technologies. Furthermore, I completed capstone projects for academic programs, demonstrating my proficiency in delivering comprehensive solutions. By developing machine learning applications and utilizing data analysis and modeling techniques, I created intelligent and predictive systems. Throughout my career, I maintained a deep understanding of the software development lifecycle and collaborated effectively with cross-functional teams to deliver high-quality applications. Staying up to date with the latest technologies and best practices, I prioritized user-centric design, maintainable code, and seamless user experiences, driving innovation in application developmen`,
        badges: [
            'Angular 16',
            'Ionic',
            'React',
            'React Native',
            'Tailwind',
            'Typescript',
            'NestJs',
            'SCSS',
            'Redux',
            'NGRX',
            'Rxjs',
            'Karma',
            'Angular MDC',
            'HTML',
            'CSS',
            'JQuery',
            'JavaScript',
            'PHP',
            'MySQL',
            'PostgreSQL',
            'IoT',
            'Machine Learning',
            'CNN',
            'Decision Tree',
            'Random Forest',
            'Linear Regression',
            'SVM',
            'OpenCV',
        ],
    },
]
